import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import { Suspense } from "react";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "LMSBuddy",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={manrope.className}>
				<ReduxProvider>
					<Suspense>{children}</Suspense>
					<Toaster />
				</ReduxProvider>
			</body>
		</html>
	);
}
