import Footer from "@/components/Welcome/Footer";
import Navbar from "@/components/Welcome/Navbar";
import React from "react";

const PrivacyPolicy = () => {
	return (
		<>
			<Navbar />
			<div className='bg-gray-50 py-10 px-6 sm:px-10 lg:px-20 text-gray-800'>
				<h1 className='text-3xl font-bold text-center mb-6'>
					Privacy Policy
				</h1>
				<p className='text-sm text-center text-gray-500 mb-4'>
					Last updated: October 21, 2024
				</p>

				<p className='mb-6'>
					This Privacy Policy describes Our policies and procedures on
					the collection, use and disclosure of Your information when
					You use the Service and tells You about Your privacy rights
					and how the law protects You.
				</p>

				<p className='mb-6'>
					We use Your Personal data to provide and improve the
					Service. By using the Service, You agree to the collection
					and use of information in accordance with this Privacy
					Policy. This Privacy Policy has been created with the help
					of the
					<a
						href='https://www.freeprivacypolicy.com/free-privacy-policy-generator/'
						className='text-blue-500 hover:underline'
						target='_blank'
						rel='noopener noreferrer'
					>
						Free Privacy Policy Generator
					</a>
					.
				</p>

				<section className='mb-8'>
					<h2 className='text-2xl font-semibold mb-4'>
						Interpretation and Definitions
					</h2>

					<h3 className='text-xl font-semibold mb-2'>
						Interpretation
					</h3>
					<p className='mb-6'>
						The words of which the initial letter is capitalized
						have meanings defined under the following conditions.
						The following definitions shall have the same meaning
						regardless of whether they appear in singular or in
						plural.
					</p>

					<h3 className='text-xl font-semibold mb-2'>Definitions</h3>
					<p className='mb-4'>
						For the purposes of this Privacy Policy:
					</p>

					<ul className='list-disc list-inside space-y-2'>
						<li>
							<strong>Account:</strong> means a unique account
							created for You to access our Service or parts of
							our Service.
						</li>
						<li>
							<strong>Affiliate:</strong> means an entity that
							controls, is controlled by or is under common
							control with a party...
						</li>
						<li>
							<strong>Application:</strong> refers to LMS Buddy,
							the software program provided by the Company.
						</li>
						<li>
							<strong>Company:</strong> (referred to as either
							"the Company", "We", "Us" or "Our" in this
							Agreement) refers to LMS Buddy.
						</li>
						<li>
							<strong>Country:</strong> refers to: Uttar Pradesh,
							India.
						</li>
						<li>
							<strong>Device:</strong> means any device that can
							access the Service such as a computer, a cellphone
							or a digital tablet.
						</li>
						<li>
							<strong>Personal Data:</strong> is any information
							that relates to an identified or identifiable
							individual.
						</li>
						<li>
							<strong>Service:</strong> refers to the Application.
						</li>
						<li>
							<strong>Service Provider:</strong> means any natural
							or legal person who processes the data on behalf of
							the Company...
						</li>
						<li>
							<strong>Usage Data:</strong> refers to data
							collected automatically, either generated by the use
							of the Service...
						</li>
						<li>
							<strong>You:</strong> means the individual accessing
							or using the Service...
						</li>
					</ul>
				</section>

				<section className='mb-8'>
					<h2 className='text-2xl font-semibold mb-4'>
						Collecting and Using Your Personal Data
					</h2>

					<h3 className='text-xl font-semibold mb-2'>
						Types of Data Collected
					</h3>

					<h4 className='text-lg font-semibold mb-2'>
						Personal Data
					</h4>
					<p className='mb-6'>
						While using Our Service, We may ask You to provide Us
						with certain personally identifiable information that
						can be used to contact or identify You. Personally
						identifiable information may include, but is not limited
						to:
					</p>

					<ul className='list-disc list-inside space-y-2 mb-6'>
						<li>Email address</li>
						<li>First name and last name</li>
						<li>Phone number</li>
						<li>Address, State, Province, ZIP/Postal code, City</li>
						<li>Usage Data</li>
					</ul>

					<h4 className='text-lg font-semibold mb-2'>Usage Data</h4>
					<p className='mb-6'>
						Usage Data is collected automatically when using the
						Service. Usage Data may include information such as Your
						Device's Internet Protocol address...
					</p>
				</section>

				<section className='mb-8'>
					<h3 className='text-xl font-semibold mb-4'>
						Use of Your Personal Data
					</h3>
					<p className='mb-6'>
						The Company may use Personal Data for the following
						purposes:
					</p>

					<ul className='list-disc list-inside space-y-2 mb-6'>
						<li>
							<strong>To provide and maintain our Service</strong>
							, including to monitor the usage of our Service.
						</li>
						<li>
							<strong>To manage Your Account:</strong> to manage
							Your registration as a user of the Service.
						</li>
						<li>
							<strong>For the performance of a contract:</strong>{" "}
							the development, compliance, and undertaking...
						</li>
						<li>
							<strong>To contact You:</strong> To contact You by
							email, telephone calls, SMS...
						</li>
						<li>
							<strong>For business transfers:</strong> We may use
							Your information to evaluate or conduct...
						</li>
						<li>
							<strong>For other purposes:</strong> We may use Your
							information for data analysis, identifying usage
							trends, etc.
						</li>
					</ul>
				</section>

				<section className='mb-8'>
					<h3 className='text-xl font-semibold mb-4'>
						Retention of Your Personal Data
					</h3>
					<p className='mb-6'>
						The Company will retain Your Personal Data only for as
						long as is necessary for the purposes set out in this
						Privacy Policy...
					</p>
				</section>

				{/* Add more sections as needed, following the same pattern */}
			</div>
			<Footer/>
		</>
	);
};

export default PrivacyPolicy;
